services:
  db:
    image: postgres:12.2-alpine
    env_file: .env
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - 127.0.0.1:${DB_PORT}:5432
    volumes:
      - ../pgdata/${DB_NAME}_development:/var/lib/postgresql/data
  redis:
    image: "redis:alpine"
    env_file: .env
    command: redis-server --save 1800 1
    ports:
      - 127.0.0.1:${REDIS_PORT}:6379
    volumes:
      - ../redis-data/${DB_NAME}_development:/data
    depends_on:
      - db
    healthcheck:
      test: [ "CMD-SHELL", "redis-cli ping | grep PONG" ]
      interval: 1s
      timeout: 3s
      retries: 5